### ISSUE TITLE
Add devices

### ISSUE THREAD

**Issue by gvanhoecke** [shamanenas/has_domintell#1]
I'm trying to add devices, but when I copy paste the code provided in the readme then it gives a parsing error in configuration.yaml ... did I paste it in the wrong file?

**Comment by dnouls** [comment]
I had the same problem.
I started from scratch and then the parsing succeeded. This YAML stuff is very picky about indentations.
This format worked for me
```
domintell:
  host: 10.0.1.10:17481
  password: LOGIN

light:
- platform: domintell
  devices:
  - type: BIR
    module: 09CD       
    channel: 1
    name: Licht Voorgevel
    location: Home|Voorgevel
```
