### ISSUE TITLE
I tried to follow the readme.md to install has_domintell but I get an error that domintell integration is not available

### ISSUE THREAD

**Issue by dnouls** [shamanenas/has_domintell#2]
This is the error I get:
Component error: domintell - Integration 'domintell' not found.
Platform error light.domintell - Integration 'domintell' not found.

This is my config:
```
domintell:
  host: 10.0.1.10:17481
  password: LOGIN

light:
- platform: domintell
  devices:
  - type: BIR
    module: 09CD       
    channel: 1
    name: Licht Voorgevel
    location: Home|Voorgevel
```
I have copied the domintell extension in
"config/custom_components/domintell" as explained in the docs here.

Please help!
